//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMwebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizador()
        {
            this.IntervencaoCurativa = new HashSet<IntervencaoCurativa>();
            this.PedidoManutCurativa = new HashSet<PedidoManutCurativa>();
            this.PedidoManutPreventiva = new HashSet<PedidoManutPreventiva>();
        }
    
        public int IDUser { get; set; }
        public int IDTipo { get; set; }
        public int NumeroUtilizador { get; set; }
        public string Nome { get; set; }
        public Nullable<int> EstadoAtividade { get; set; }
        public string DataInativacao { get; set; }
    
        public virtual Autenticacao Autenticacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntervencaoCurativa> IntervencaoCurativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoManutCurativa> PedidoManutCurativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoManutPreventiva> PedidoManutPreventiva { get; set; }
        public virtual TipoUtilizador TipoUtilizador { get; set; }
    }
}
